--- #YAML:1.0
name:               Proc-InvokeEditor
version:            1.07
abstract:           Interface to external editor from perl
author:
    - Michael Stevens <mstevens@etla.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp::Assert:  0.11
    File::Spec:    0.82
    File::Temp:    0.12
    IPC::Cmd:      0
    Test::More:    0.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
